# Generated by Django 4.2.4 on 2023-08-17 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
